name: Prueba unitaria

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Reemplaza '3.x' con la versión de Python que necesites
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Asegúrate de tener un archivo requirements.txt si tienes dependencias
      - name: Ejecutar prueba unitaria
        run: |
          python -m unittest test.py
